# Generated by Django 3.2 on 2021-08-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoir', '0002_auto_20210807_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='Content',
            new_name='content',
        ),
    ]
