# Generated by Django 3.2 on 2021-08-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoir', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
    ]
