# Generated by Django 3.2 on 2021-08-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoir', '0005_auto_20210812_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='image',
        ),
    ]
